---
- hosts: 172.31.24.49
  become: yes
  tasks:
    - include_tasks: createnewfile.yml
    - name: copy file to node
      copy:
        src: test.txt
        dest: /home/vinitha/welcome
    - name: download from the url
      get_url:
        url: https://adp-mirror-vm1-he-fi.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20-deployer.tar.gz
        dest: /home/vinitha
        force_basic_auth: yes
    - name: copy index.j2 into node
      template:
        src: index.j2
        dest: /var/www/html/index.html
      notify: restart web server
    handlers:
    - name: restart web server
      service:
        name: apache2
        state: restarted