---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install httpd server
    dnf:
      name: "{{mywebpack}}"
      state: present
  - name: start web server
    service:
      name: "{{mywebpack}}"
      state: started
