---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install webserver on redhat node side
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"
  - name: start web server
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"
  - name: install webserver on debian node side
    apt:
      name: "{{mywebpackondebian}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: start web server
    service:
      name: "{{mywebpackondebian}}"
      state: started
    when: ansible_os_family=="Debian"

