---
- hosts: all
  become: yes
  tasks:
  - name: install httpd server
    dnf:
      name: httpd
      state: present
  - name: start web server
    service:
      name: start web server
      state: started
