---
- hosts: 172.31.24.49
  become: yes
  tasks:
    - name: execute linux command
      command:
        name: hostname -f
      register: myresult
    - name: save result
      debug:
        msg: "{{myresult}}"