---
- hosts: 172.31.24.49
  become: yes
  task:
    - name: install git
      apt:
        name: git
        state: present
      tags: mygit
    - name: install tree
      apt:
        name: tree
        state: present
      tags: mytree
    - name: install wget
      apt:
        name: wget
        state: present
      tags: mywget